version: '3'
services:

  db:
    image: postgres
    restart: on-failure
    container_name: postgresdb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: testwalletdb
    healthcheck:
      test: pg_isready -d postgres
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "5032:5432"
      - ${KC_POSTGRES_PORT_MAPPING:-5435}:5432
    volumes:
      - ./docker/pg_data:/var/lib/postgresql/data

  redis:
    image: 'redis:latest'
    container_name: redis-master
    environment:
      - REDIS_PASSWORD=123321
    ports:
      - "6000:6379"
    volumes:
      - ./docker/redis/redis_log:/log
      - ./docker/redis/redis_conf:/conf
      - ./docker/redis/redis_data:/data
    command: redis-server --save 900 1 --appendonly yes