version: '3'
services:

  db:
    image: postgres
    restart: on-failure
    container_name: postgresdb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: spring
    healthcheck:
      test: pg_isready -d postgres
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "5032:5432"
      - ${KC_POSTGRES_PORT_MAPPING:-5435}:5432
    volumes:
      - ./docker/pg_data:/var/lib/postgresql/data

  redis:
    image: 'redis:latest'
    container_name: redis-master
    environment:
      - REDIS_PASSWORD=123321
    ports:
      - "6000:6379"
    volumes:
      - ./docker/redis/redis_log:/log
      - ./docker/redis/redis_conf:/conf
      - ./docker/redis/redis_data:/data
    command: redis-server --save 900 1 --appendonly yes


  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: keycloak
    command:
      - start --auto-build --db postgres --hostname-strict-https false --hostname-strict false --proxy edge --http-enabled true --import-realm --spi-user-profile-legacy-user-profile-read-only-attributes *_RES_ACCESS_MODE
    environment:
      KC_DB_URL: jdbc:postgresql://db:5432/spring
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: 123321
      KC_DB_SCHEMA: keycloak
      KC_FEATURES: preview
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 123321
    ports:
      - "8282:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8080/realms/master" ]
      interval: 30s
      retries: 3
      timeout: 5s
    depends_on:
      - db