spring:
  datasource:
    url: jdbc:postgresql://localhost:5032/testwalletdb
    #    url: jdbc:postgresql://postgresdb:5432/testwalletdb
    username: root
    password: 123321
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/changelog.xml
    default-schema: changelog
    liquibase-schema: changelog
  application:
    name: wallet-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8282/realms/mentalism
          jwk-set-uri: http://localhost:8282/realms/mentalism/protocol/openid-connect/certs

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: '8080'

keycloak:
  token-url: http://localhost:8282/realms/mentalism/protocol/openid-connect/token
  introspect-url: http://localhost:8282/realms/mentalism/protocol/openid-connect/token/introspect
  client-id: wallet-client
  client-secret: aPSNa2sFWT2SPUJv7HxWGXoJ54mcLFgh