spring:
  datasource:
    url: jdbc:postgresql://localhost:5032/testwalletdb
    username: root
    password: 123321
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: /db/changelog/changelog.xml
    default-schema: changelog

keycloak:
  client_url: http://localhost:8282/realms/wallet-realm/protocol/openid-connect/token
  admin_url: http://localhost:8282/realms/master/protocol/openid-connect/token
  users_url: http://localhost:8282/admin/realms/wallet-realm/users
  admin_username: admin
  admin_password: 123321
  secret: YVCAPKM703ILhKCqJ4xdOWzWpFxvB1MQ
  public_rsa_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyXxcERyn/QzAfmGmVrv7BPY90HPlKpye0BhvOXeN6X0tOIF+QYdWPKNsW6tJ7BzR8u9DVFvvNilrdtc024a6uRxUDMpz/o6sWix2izPRqsrYfGBzo4BoYo/eaY6yWmi20UI6pWcLMSoDTVyI6AFdOtAWCTWRGSWf1vT2Luy0SAt/UbDd3Oz6H74aj8YZYAw1ncgVuCU+pmQz8m5xyi6XmHNChraaYXAVaxx24zxzCFs7rqr0h2kB1xztIMgSb3hQfIBVdxCnmVGMR7zLJnXBTEV8ALyCGEla2dcmpvaznkvJKW2oJaJvm24bBoI51fL5wm7lnaQgovdpbfZuyvUPcQIDAQAB