spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false

  datasource:
    url: jdbc:postgresql://localhost:5032/spring
    username: root
    password: 123321
    driver-class-name: org.postgresql.Driver
  liquibase:
  #  liquibase:
    change-log: db/changelog/changelog.yml
    default-schema: changelog
    liquibase-schema: changelog
  data:
    redis:
      host: localhost
      port: 6000
      password: 123321


  application:
    name: wallet-service





logging:
  level:
    org.springframework.security: DEBUG

server:
  port: '8080'

keycloak:
  token-url: http://localhost:8282/realms/mentalism/protocol/openid-connect/token
  introspect-url: http://localhost:8282/realms/mentalism/protocol/openid-connect/token/introspect
  client-id: wallet-client
  client-secret: aPSNa2sFWT2SPUJv7HxWGXoJ54mcLFgh