spring:
  datasource:
    url: jdbc:postgresql://localhost:5032/testwalletdb
    #    url: jdbc:postgresql://postgresdb:5432/testwalletdb
    username: root
    password: 123321
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/changelog.xml
    default-schema: changelog
  application:
    name: wallet-service

  security:
    oauth2:
      client:
        provider:
          wallet-realm:
            issuer-uri: http://localhost:8282/realms/wallet-realm
        registration:
          wallet-realm:
            provider: wallet-realm
            client-name: wallet-client
            client-id: wallet-client
            client-secret: bO06LhYXKple5KnVwXCqjFE6lJkKXUnJ
            scope:
              - openid
              - offline_access
              - profile
            authorization-grant-type: password
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8282/realms/wallet-realm
          jwk-set-uri: http://localhost:8282/realms/wallet-realm/protocol/openid-connect/certs

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: '8080'