version: '3'
services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: mentalism
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: testwalletdb
    ports:
      - "5032:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
